# Generated by Django 4.2.1 on 2023-06-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_habitacion',
            fields=[
                ('id_tipo_habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tipo', models.CharField(max_length=50)),
                ('descrip_tipo', models.TextField(null=True)),
            ],
        ),
    ]
