# Generated by Django 4.2.1 on 2023-06-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_habitacion',
            name='precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
