# Generated by Django 4.2.1 on 2023-06-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='dv',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='run',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
