# Generated by Django 4.2.1 on 2023-06-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cliente_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='id_habitacion',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tipo_habitacion',
            name='nom_tipo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
