# Generated by Django 4.2.1 on 2023-06-15 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_cliente_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='user',
            new_name='usuario',
        ),
    ]
