# Generated by Django 4.2.1 on 2023-06-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_cliente_primer_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='primer_nombre',
            field=models.CharField(max_length=30),
        ),
    ]
