# Generated by Django 4.2.1 on 2023-06-16 00:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_cliente_primer_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='primer_nombre',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Ingrese solo letras')]),
        ),
    ]
