# Generated by Django 4.2.1 on 2023-06-16 02:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_cliente_primer_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido_materno',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Ingrese solo letras')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido_paterno',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Ingrese solo letras')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='segundo_nombre',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Ingrese solo letras')]),
        ),
        migrations.AlterField(
            model_name='tipo_habitacion',
            name='nom_tipo',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Ingrese solo letras')]),
        ),
    ]
