# Generated by Django 4.2.1 on 2023-06-20 22:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_cliente_apellido_materno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reservacion', models.DateField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('total_reserva', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('run_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cliente')),
            ],
        ),
    ]
